/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppStoreLogDrawer: typeof import('./src/components/AppStoreLogDrawer.vue')['default']
    Breadcrumb: typeof import('./src/components/Breadcrumb/index.vue')['default']
    CodeEditor: typeof import('./src/components/CodeEditor.vue')['default']
    CronRunHistory: typeof import('./src/components/CronRunHistory.vue')['default']
    DirPicker: typeof import('./src/components/DirPicker.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    FilePicker: typeof import('./src/components/FilePicker.vue')['default']
    Hamburger: typeof import('./src/components/Hamburger/index.vue')['default']
    MonitorRangePicker: typeof import('./src/components/MonitorRangePicker.vue')['default']
    NavPillPanels: typeof import('./src/components/NavPillPanels.vue')['default']
    Permission: typeof import('./src/components/Permission/index.vue')['default']
    PluginSlot: typeof import('./src/components/PluginSlot.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemMonitor: typeof import('./src/components/SystemMonitor.vue')['default']
    TaskQueuePanel: typeof import('./src/components/TaskQueuePanel.vue')['default']
  }
}
